version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  hbase:
    image: harisekhon/hbase:latest
    container_name: hbase
    ports:
      - "16010:16010"  # Web UI
      - "9090:9090"    # Thrift API
      - "2181:2181"    # Zookeeper
    environment:
      - HBASE_CONF_hbase_rootdir=/data/hbase
      - HBASE_THRIFT=true
    command: >
      sh -c "
        /entrypoint.sh &&
        sleep 5 &&
        hbase thrift start -p 9090 --infoport 9095
      "  
    volumes:
      - hbase-data:/data

  hbase-client:
    image: python:3.10-slim
    container_name: hbase-client
    depends_on:
      - hbase
    working_dir: /app
    volumes:
      - ./hbase_analytics:/app
    command: tail -f /dev/null


volumes:
  hbase-data:

