version: '3.8'

services:
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "16010:16010"  # Web UI
      - "9090:9090"    # Thrift
    environment:
      HBASE_THRIFT: "yes"

  hbase-client:
    build:
      context: ./hbase_queries
    container_name: hbase-client
    depends_on:
      - hbase
    networks:
      - hbase_net

networks:
  hbase_net:
    driver: bridge
