services:  # <-- Todos los servicios deben ir dentro de esta sección
  hbase:
    image: harisekhon/hbase
    container_name: hbase
    ports:
      - "9090:9090"
      - "16010:16010"
    networks:
      - mynet

  analytics:
    build:
      context: ./analytics
    container_name: analytics
    depends_on:
      - hbase
    networks:
      - mynet
    volumes:
      - ./datos_kaggle:/data

  hbase-client:
    image: harisekhon/hbase
    container_name: hbase-client
    entrypoint: /bin/bash
    tty: true
    networks:
      - mynet

networks:
  mynet:
