services:
  hbase:
    image: harisekhon/hbase
    platform: linux/amd64
    ports:
      - "16010:16010"
      - "9090:9090"
    environment:
      HBASE_MANAGES_ZK: "true"

  consumer:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./consumer.py:/app/consumer.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    command: /bin/sh -c "pip install -r requirements.txt && python consumer.py"
    depends_on:
      - hbase

  analytics:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    command: python analytics_queries.py
    depends_on:
      - hbase
